import { Column, DataType, Model, Table } from "sequelize-typescript";
import { ApiProperty } from "@nestjs/swagger";
interface ITasksAttrs {
  name: string;
  status: string;
  priority: string;
  description: string;
  dueDate: string;
  statusId: number;
}

@Table({ tableName: "tasks" })
export class Task extends Model<Task, ITasksAttrs> {
  @ApiProperty({ example: 1, description: "unique autogenerated ID" })
  @Column({
    type: DataType.INTEGER,
    unique: true,
    autoIncrement: true,
    primaryKey: true,
  })
  id!: number;

  @ApiProperty({ example: "Home cleaning", description: "name of task" })
  @Column({
    type: DataType.STRING,
    allowNull: false,
  })
  name!: string;

  @ApiProperty({ example: "In process", description: "task status" })
  @Column({
    type: DataType.STRING,
    allowNull: false,
  })
  status!: string;

  @ApiProperty({ example: 1, description: "task status id" })
  @Column({
    type: DataType.INTEGER,
    allowNull: false,
  })
  statusId!: number;

  @ApiProperty({ example: "low", description: "priority" })
  @Column({
    type: DataType.STRING,
    allowNull: false,
  })
  priority!: string;

  @ApiProperty({
    example: "2024-03-22 15:19:49.732+02",
    description: "Due Date",
  })
  @Column({
    type: DataType.DATE,
    allowNull: false,
  })
  dueDate!: string;

  @ApiProperty({
    example: "It`s important task, for clean house",
    description: "Task description",
  })
  @Column({
    type: DataType.TEXT,
    allowNull: false,
  })
  description!: string;
}
